# Table 2: Summary statistics

In [1]:
source('../scripts/load_libraries.R')
source('../scripts/load_constants.R')


Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


Loading required package: Matrix


Attaching package: ‘tidyr’


The following objects are masked from ‘package:Matrix’:

    expand, pack, unpack



Attaching package: ‘lubridate’


The following objects are masked from ‘package:base’:

    date, intersect, setdiff, union



Please cite as: 


 Hlavac, Marek (2018). stargazer: Well-Formatted Regression and Summary Statistics Tables.

 R package version 5.2.2. https://CRAN.R-project.org/package=stargazer 



Attaching package: ‘lemon’


The following objects are masked from ‘package:ggplot2’:

    CoordCartesian, element_render




In [2]:
source('../scripts/load_data.R')

Rows: 17264341 Columns: 5
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: ","
dbl (5): comment_id, user_id, author_id, anonymous, first_view

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 1281001 Columns: 4
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: ","
dbl (4): comment_id, user_id, score, time_stamp

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 223737 Columns: 4
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: ","
dbl (4): comment_id, user_id, num, time_stamp

ℹ Use `spec()` t

In [3]:
all_comments <- read_csv('../data/comments_cleaned.csv', 
                         col_types = list(comment_id = col_integer(),
                                          story_id = col_integer()))

In [4]:
df3 <- df_clean %>%
  inner_join(all_comments %>% select(comment_id, story_id))

Joining, by = "comment_id"


In [5]:
df3 %>%
  summarise(
    `Comment Exposures` = n(),
    `Unique Articles` = n_distinct(story_id),
    `Unique Comments` = n_distinct(comment_id),
    `Unique Commenters` = n_distinct(author_id),
    `Unique Viewers` = n_distinct(user_id),
    `Unique Pairs` = n_distinct(user_id * 1000000 + author_id),
  ) %>%
  t()

[,1]    
Comment Exposures 12623814
Unique Articles      32930
Unique Comments     346559
Unique Commenters     3725
Unique Viewers        6415
Unique Pairs        737007

In [6]:
df3 %>%
  group_by(identified) %>%
  summarise(
    `Comment Exposures` = n(),
    `Unique Articles` = n_distinct(story_id),
    `Unique Comments` = n_distinct(comment_id),
    `Unique Commenters` = n_distinct(author_id),
    `Unique Viewers` = n_distinct(user_id),
    `Unique Pairs` = n_distinct(user_id * 1000000 + author_id),
  ) %>%
  t()

[,1]   [,2]    
identified             0        1
Comment Exposures 632855 11990959
Unique Articles    25176    32910
Unique Comments   227066   346469
Unique Commenters   2944     3723
Unique Viewers      4086     6393
Unique Pairs      181919   721787

In [7]:
df3 %>%
  summarise(
    `Pr(Up)` = mean(up),
    `Pr(Dn)` = mean(dn),
    `Pr(Rp)` = mean(rp),
  ) %>%
  t()

[,1]       
Pr(Up) 0.042400181
Pr(Dn) 0.010869298
Pr(Rp) 0.009298537

In [8]:
df3 %>%
  group_by(identified) %>%
  summarise(
    `Pr(Up)` = mean(up),
    `Pr(Dn)` = mean(dn),
    `Pr(Rp)` = mean(rp),
  ) %>%
  t()

[,1]        [,2]       
identified 0.000000000 1.000000000
Pr(Up)     0.040546413 0.042498019
Pr(Dn)     0.010296197 0.010899545
Pr(Rp)     0.008657591 0.009332364

In [9]:
df3 %>%
  group_by(story_id) %>%
  summarise(comments = n_distinct(comment_id)) %>%
  summarise(`Comments / Article` = mean(comments))

Comments / Article
1 10.52411

In [10]:
df3 %>%
  group_by(author_id) %>%
  summarise(comments = n_distinct(comment_id)) %>%
  summarise(`Comments / Commenter` = mean(comments))

Comments / Commenter
1 93.03597

In [11]:
df3 %>%
  group_by(user_id) %>%
  summarise(exposures = n(), up = sum(up), dn = sum(dn), rp = sum(rp)) %>%
  summarise(`Exposures / Viewer` = mean(exposures),
            `Up-votes / Viewer` = mean(up),
            `Down-votes / Viewer` = mean(dn),
            `Replies / Viewer` = mean(rp),
           ) %>%
  t()

[,1]      
Exposures / Viewer  1967.85877
Up-votes / Viewer     83.43757
Down-votes / Viewer   21.38924
Replies / Viewer      18.29821

In [12]:
df3 %>%
  group_by(identified, user_id) %>%
  summarise(exposures = n()) %>%
  summarise(`Exposures / Viewer` = mean(exposures))

`summarise()` has grouped output by 'identified'. You can override using the `.groups` argument.


identified Exposures / Viewer
1 0           154.8837         
2 1          1875.6388

In [13]:
df3 %>%
  group_by(comment_id) %>%
  summarise(exposures = n(), up = sum(up), dn = sum(dn), rp = sum(rp)) %>%
  summarise(`Exposures / Comment` = mean(exposures),
            `Up-votes / Comment` = mean(up),
            `Down-votes / Comment` = mean(dn),
            `Replies / Comment` = mean(rp),
           ) %>%
  t()

[,1]      
Exposures / Comment  36.4261612
Up-votes / Comment    1.5444758
Down-votes / Comment  0.3959268
Replies / Comment     0.3387100

In [14]:
df3 %>%
  group_by(identified, comment_id) %>%
  summarise(exposures = n(), up = sum(up), dn = sum(dn), rp = sum(rp)) %>%
  summarise(`Exposures / Comment` = mean(exposures),
            `Up-votes / Comment` = mean(up),
            `Down-votes / Comment` = mean(dn),
            `Replies / Comment` = mean(rp),
           ) %>%
  t()

`summarise()` has grouped output by 'identified'. You can override using the `.groups` argument.


[,1]       [,2]      
identified           0.00000000  1.0000000
Exposures / Comment  2.78709714 34.6090386
Up-votes / Comment   0.11300679  1.4708156
Down-votes / Comment 0.02869650  0.3772228
Replies / Comment    0.02412955  0.3229842